# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-11 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_article_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('dv', 'development'), ('ps', 'personal')], default='dv', max_length=2),
        ),
    ]
